apiVersion: v1
kind: Service
metadata:
  name: app-service-test
  labels:
    app: app-service
    version: v1
spec:
  selector:
    app: "app-service"
  type: "LoadBalancer"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
