apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: davescott99/app-k8s
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-test
  labels:
    app: app-service
    version: v1
spec:
  selector:
    app: "app-service"
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
