apiVersion: v1
kind: Namespace
metadata:
  name: app-service2
  labels:
    name: app-service2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service2
  namespace: app-service2
  labels:
    app: app-service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service2
  template:
    metadata:
      labels:
        app: app-service2
    spec:
      containers:
        - name: app-service2
          image: davescott99/app-k8s
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service2-test
  namespace: app-service2
  labels:
    app: app-service2
    version: v1
spec:
  selector:
    app: "app-service2"
  type: "LoadBalancer"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
